---
module_root: modules/
modules:
 #~ - name: test
   #~ file: testmodule.so

 -  name: sender
    file: comm_sender.so

 -  name: baselink
    file: baselink.so
    configuration:
        receive_flight_commands: true
        send_flight_data: true
        port: /dev/pts/7
        reference_timeout: 10000000.0

 -  name: observer
    file: observer.so
    configuration: /home/shared/projects/crap/modules/observer/configuration.yaml

 -  name: controller
    file: controller.so
    configuration: /home/shared/projects/crap/modules/controller/configuration.yaml

 #~ -  name: sensor_reader
    #~ file: sensor_reader.so
    #~ configuration:
        #~ use_smcu:   Yes
        #~ smcu_port:  /dev/ttyS0
        #~ use_cmcu:   No
        #~ cmcu_port:  /dev/ttyS2

 -  name: logic
    file: logic.so
    configuration:
        frequency: 50
        initial_mode: hover
        modes:
            directory: flightmodes/
            extension: .so
