---
module_root: modules/
modules:
 #~ - name: test
   #~ file: testmodule.so

 -  name: sender
    file: comm_sender.so
#~
 #~ -  name: receiver
    #~ file: comm_receiver.so
    #~ configuration: test

 -  name: observer
    file: observer.so
    configuration: test

 -  name: controller
    file: controller.so
    configuration: controller_config.yaml

 -  name: sensor_reader
    file: sensor_reader.so
    configuration:
        use_smcu:   Yes
        smcu_port:  /dev/ttyS0
        use_cmcu:   No
        cmcu_port:  /dev/ttyS2

 -  name: logic
    file: logic.so
    configuration:
        frequency: 50
        initial_mode: hover
        modes:
            directory: flightmodes/
            extension: .so
