---
module_root: modules/
config_root: /home/shared/projects/crap/configuration/
modules:
 -  name: sender
    file: comm_sender.so

 -  name: baselink
    file: baselink.so
    configuration:
        receive_flight_commands: true
        send_flight_data: true
        port: /dev/pts/13
        reference_timeout: 10.0

 -  name: observer
    file: observer.so
    configuration: observer.yaml

 -  name: reality
    file: reality.so
    configuration: reality.yaml

 -  name: controller
    file: controller.so
    configuration: controller.yaml

 -  name: sensor_reader
    file: sensor_reader.so
    configuration: sensor_reader.yaml

 -  name: camera_reader
    file: camera_reader.so
    configuration: camera_reader.yaml

 -  name: logic
    file: logic.so
    configuration:
        frequency: 50
        initial_mode: acrobat
        modes:
            directory: flightmodes/
            configuration_directory: /home/shared/projects/crap/configuration/modes/
            extension: .so
