---
port: /dev/pts/14
input_range:
    - [365,423]
    - [404,431]
    - [395,423]
    - [381,380]
    - [333,430]
    - [371,358]


output_range:
    x: 0.5
    y: 0.5
    z: 0.5
    rx: 1
    ry: 1
    rz: 1

directories:
    root: /home/shared/projects/crap/
    element_files: interface/elements/
    element_objects: build/elements/

window:
    id: win
    width: 800
    height: 600

    near: 1.0
    far: 80.0

    children:
        -   id: camera
            type: camera
            children:
                -   id: skybox
                    type: skybox
                -   id: ground
                    type: ground
                -   id: flyer
                    type: flyer
                    model: mh6.obj
                    scale: 0.01
