/**
 * Copyright 2011, 2012 Jonatan Olofsson
 *
 * This file is part of C++ Robot Automation Platform (CRAP).
 *
 * CRAP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CRAP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CRAP.  If not, see <http://www.gnu.org/licenses/>.
 */


#ifndef CRAP_LINKQUAD_SERIAL_DATA
#define CRAP_LINKQUAD_SERIAL_DATA

#include <cstring>
#include <string>
#include <assert.h>

#include "PP/repeat.hpp"
#include "PP/comma_if.hpp"
#include "PP/plus_if.hpp"

#include <stdint.h> // type definitions


#define MAX_NUM_DATAMEMBERS 158

namespace LinkQuad {
    namespace comm {
        namespace serial {
#include "link_api/messages.h"
#include "link_api/packet.h"
            namespace data {
                struct nothing { static const uint8_t c = 0; static const uint8_t size = 0; static const uint8_t n = 0; static void set(const uint8_t*){} static void get(uint8_t*){}};

                namespace request_part {
                    template<int TYPE, int N> struct DataRequestPart;
                }

                namespace SSMCU {
                    typedef request_part::DataRequestPart<MSG_SMCU_DATA_PART_REQUEST, 66> Part;

                    struct iReftime_t { typedef uint32_t type; static const size_t size = sizeof(type); type iReftime; static const uint8_t c = 1; static const uint8_t n = 0; void set(const uint8_t*& v){memcpy(&iReftime, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iReftime, sizeof(type)); v += sizeof(type); } }; typedef iReftime_t iReftime;
                    struct gyro_data_t { typedef int16_t type[3]; static const size_t size = sizeof(type); type gyro_data; static const uint8_t c = 1; static const uint8_t n = 1; void set(const uint8_t*& v){memcpy(&gyro_data, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gyro_data, sizeof(type)); v += sizeof(type); } }; typedef gyro_data_t gyro_data;
                    struct gyro_raw_t { typedef int16_t type[3]; static const size_t size = sizeof(type); type gyro_raw; static const uint8_t c = 1; static const uint8_t n = 2; void set(const uint8_t*& v){memcpy(&gyro_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gyro_raw, sizeof(type)); v += sizeof(type); } }; typedef gyro_raw_t gyro_raw;
                    struct gyro_temp_raw_t { typedef int16_t type[3]; static const size_t size = sizeof(type); type gyro_temp_raw; static const uint8_t c = 1; static const uint8_t n = 3; void set(const uint8_t*& v){memcpy(&gyro_temp_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gyro_temp_raw, sizeof(type)); v += sizeof(type); } }; typedef gyro_temp_raw_t gyro_temp_raw;
                    struct accel_raw_t { typedef int16_t type[3]; static const size_t size = sizeof(type); type accel_raw; static const uint8_t c = 1; static const uint8_t n = 4; void set(const uint8_t*& v){memcpy(&accel_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &accel_raw, sizeof(type)); v += sizeof(type); } }; typedef accel_raw_t accel_raw;
                    struct micromag_t { typedef int16_t type[3]; static const size_t size = sizeof(type); type micromag; static const uint8_t c = 1; static const uint8_t n = 5; void set(const uint8_t*& v){memcpy(&micromag, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &micromag, sizeof(type)); v += sizeof(type); } }; typedef micromag_t micromag;
                    struct ahrs_t { typedef int16_t type[3]; static const size_t size = sizeof(type); type ahrs; static const uint8_t c = 1; static const uint8_t n = 6; void set(const uint8_t*& v){memcpy(&ahrs, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ahrs, sizeof(type)); v += sizeof(type); } }; typedef ahrs_t ahrs;
                    struct compass_heading_t { typedef int16_t type; static const size_t size = sizeof(type); type compass_heading; static const uint8_t c = 1; static const uint8_t n = 7; void set(const uint8_t*& v){memcpy(&compass_heading, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &compass_heading, sizeof(type)); v += sizeof(type); } }; typedef compass_heading_t compass_heading;
                    struct rc_sticks_t { typedef int16_t type[7]; static const size_t size = sizeof(type); type rc_sticks; static const uint8_t c = 1; static const uint8_t n = 8; void set(const uint8_t*& v){memcpy(&rc_sticks, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_t rc_sticks;
                    struct battery_voltage_t { typedef int16_t type; static const size_t size = sizeof(type); type battery_voltage; static const uint8_t c = 1; static const uint8_t n = 9; void set(const uint8_t*& v){memcpy(&battery_voltage, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &battery_voltage, sizeof(type)); v += sizeof(type); } }; typedef battery_voltage_t battery_voltage;
                    struct cGPSValid_t { typedef int8_t type; static const size_t size = sizeof(type); type cGPSValid; static const uint8_t c = 1; static const uint8_t n = 10; void set(const uint8_t*& v){memcpy(&cGPSValid, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &cGPSValid, sizeof(type)); v += sizeof(type); } }; typedef cGPSValid_t cGPSValid;
                    struct iLatDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type iLatDeg; static const uint8_t c = 1; static const uint8_t n = 11; void set(const uint8_t*& v){memcpy(&iLatDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iLatDeg, sizeof(type)); v += sizeof(type); } }; typedef iLatDeg_t iLatDeg;
                    struct iLonDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type iLonDeg; static const uint8_t c = 1; static const uint8_t n = 12; void set(const uint8_t*& v){memcpy(&iLonDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iLonDeg, sizeof(type)); v += sizeof(type); } }; typedef iLonDeg_t iLonDeg;
                    struct fAlt_t { typedef float type; static const size_t size = sizeof(type); type fAlt; static const uint8_t c = 1; static const uint8_t n = 13; void set(const uint8_t*& v){memcpy(&fAlt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fAlt, sizeof(type)); v += sizeof(type); } }; typedef fAlt_t fAlt;
                    struct iGpsLatDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type iGpsLatDeg; static const uint8_t c = 1; static const uint8_t n = 14; void set(const uint8_t*& v){memcpy(&iGpsLatDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsLatDeg, sizeof(type)); v += sizeof(type); } }; typedef iGpsLatDeg_t iGpsLatDeg;
                    struct iGpsLonDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type iGpsLonDeg; static const uint8_t c = 1; static const uint8_t n = 15; void set(const uint8_t*& v){memcpy(&iGpsLonDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsLonDeg, sizeof(type)); v += sizeof(type); } }; typedef iGpsLonDeg_t iGpsLonDeg;
                    struct iGpsAlt_t { typedef int32_t type; static const size_t size = sizeof(type); type iGpsAlt; static const uint8_t c = 1; static const uint8_t n = 16; void set(const uint8_t*& v){memcpy(&iGpsAlt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsAlt, sizeof(type)); v += sizeof(type); } }; typedef iGpsAlt_t iGpsAlt;
                    struct siGpsYawDeg_t { typedef int16_t type; static const size_t size = sizeof(type); type siGpsYawDeg; static const uint8_t c = 1; static const uint8_t n = 17; void set(const uint8_t*& v){memcpy(&siGpsYawDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &siGpsYawDeg, sizeof(type)); v += sizeof(type); } }; typedef siGpsYawDeg_t siGpsYawDeg;
                    struct ucGpsStatus_t { typedef uint8_t type; static const size_t size = sizeof(type); type ucGpsStatus; static const uint8_t c = 1; static const uint8_t n = 18; void set(const uint8_t*& v){memcpy(&ucGpsStatus, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ucGpsStatus, sizeof(type)); v += sizeof(type); } }; typedef ucGpsStatus_t ucGpsStatus;
                    struct ucGpsStatusFlags_t { typedef uint8_t type; static const size_t size = sizeof(type); type ucGpsStatusFlags; static const uint8_t c = 1; static const uint8_t n = 19; void set(const uint8_t*& v){memcpy(&ucGpsStatusFlags, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ucGpsStatusFlags, sizeof(type)); v += sizeof(type); } }; typedef ucGpsStatusFlags_t ucGpsStatusFlags;
                    struct gDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type gDop; static const uint8_t c = 1; static const uint8_t n = 20; void set(const uint8_t*& v){memcpy(&gDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gDop, sizeof(type)); v += sizeof(type); } }; typedef gDop_t gDop;
                    struct pDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type pDop; static const uint8_t c = 1; static const uint8_t n = 21; void set(const uint8_t*& v){memcpy(&pDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &pDop, sizeof(type)); v += sizeof(type); } }; typedef pDop_t pDop;
                    struct hDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type hDop; static const uint8_t c = 1; static const uint8_t n = 22; void set(const uint8_t*& v){memcpy(&hDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &hDop, sizeof(type)); v += sizeof(type); } }; typedef hDop_t hDop;
                    struct vDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type vDop; static const uint8_t c = 1; static const uint8_t n = 23; void set(const uint8_t*& v){memcpy(&vDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &vDop, sizeof(type)); v += sizeof(type); } }; typedef vDop_t vDop;
                    struct num_SV_t { typedef uint8_t type; static const size_t size = sizeof(type); type num_SV; static const uint8_t c = 1; static const uint8_t n = 24; void set(const uint8_t*& v){memcpy(&num_SV, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &num_SV, sizeof(type)); v += sizeof(type); } }; typedef num_SV_t num_SV;
                    struct iGpsVelN_t { typedef int16_t type; static const size_t size = sizeof(type); type iGpsVelN; static const uint8_t c = 1; static const uint8_t n = 25; void set(const uint8_t*& v){memcpy(&iGpsVelN, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVelN, sizeof(type)); v += sizeof(type); } }; typedef iGpsVelN_t iGpsVelN;
                    struct iGpsVelE_t { typedef int16_t type; static const size_t size = sizeof(type); type iGpsVelE; static const uint8_t c = 1; static const uint8_t n = 26; void set(const uint8_t*& v){memcpy(&iGpsVelE, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVelE, sizeof(type)); v += sizeof(type); } }; typedef iGpsVelE_t iGpsVelE;
                    struct iGpsVelD_t { typedef int16_t type; static const size_t size = sizeof(type); type iGpsVelD; static const uint8_t c = 1; static const uint8_t n = 27; void set(const uint8_t*& v){memcpy(&iGpsVelD, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVelD, sizeof(type)); v += sizeof(type); } }; typedef iGpsVelD_t iGpsVelD;
                    struct iGpsSAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsSAcc; static const uint8_t c = 1; static const uint8_t n = 28; void set(const uint8_t*& v){memcpy(&iGpsSAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsSAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsSAcc_t iGpsSAcc;
                    struct iGpsPAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsPAcc; static const uint8_t c = 1; static const uint8_t n = 29; void set(const uint8_t*& v){memcpy(&iGpsPAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsPAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsPAcc_t iGpsPAcc;
                    struct iGpsHAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsHAcc; static const uint8_t c = 1; static const uint8_t n = 30; void set(const uint8_t*& v){memcpy(&iGpsHAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsHAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsHAcc_t iGpsHAcc;
                    struct iGpsVAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsVAcc; static const uint8_t c = 1; static const uint8_t n = 31; void set(const uint8_t*& v){memcpy(&iGpsVAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsVAcc_t iGpsVAcc;
                    struct system_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type system_status; static const uint8_t c = 1; static const uint8_t n = 32; void set(const uint8_t*& v){memcpy(&system_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &system_status, sizeof(type)); v += sizeof(type); } }; typedef system_status_t system_status;
                    struct usiError_t { typedef uint16_t type; static const size_t size = sizeof(type); type usiError; static const uint8_t c = 1; static const uint8_t n = 33; void set(const uint8_t*& v){memcpy(&usiError, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &usiError, sizeof(type)); v += sizeof(type); } }; typedef usiError_t usiError;
                    struct remote_controller_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type remote_controller_status; static const uint8_t c = 1; static const uint8_t n = 34; void set(const uint8_t*& v){memcpy(&remote_controller_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &remote_controller_status, sizeof(type)); v += sizeof(type); } }; typedef remote_controller_status_t remote_controller_status;
                    struct adc_t { typedef uint16_t type[3]; static const size_t size = sizeof(type); type adc; static const uint8_t c = 1; static const uint8_t n = 35; void set(const uint8_t*& v){memcpy(&adc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &adc, sizeof(type)); v += sizeof(type); } }; typedef adc_t adc;
                    struct ext_uart_crc_error_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type ext_uart_crc_error_cnt; static const uint8_t c = 1; static const uint8_t n = 36; void set(const uint8_t*& v){memcpy(&ext_uart_crc_error_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ext_uart_crc_error_cnt, sizeof(type)); v += sizeof(type); } }; typedef ext_uart_crc_error_cnt_t ext_uart_crc_error_cnt;
                    struct ext_uart_tx_overflow_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type ext_uart_tx_overflow_cnt; static const uint8_t c = 1; static const uint8_t n = 37; void set(const uint8_t*& v){memcpy(&ext_uart_tx_overflow_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ext_uart_tx_overflow_cnt, sizeof(type)); v += sizeof(type); } }; typedef ext_uart_tx_overflow_cnt_t ext_uart_tx_overflow_cnt;
                    struct fAltCF_t { typedef float type; static const size_t size = sizeof(type); type fAltCF; static const uint8_t c = 1; static const uint8_t n = 38; void set(const uint8_t*& v){memcpy(&fAltCF, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fAltCF, sizeof(type)); v += sizeof(type); } }; typedef fAltCF_t fAltCF;
                    struct fVelU_t { typedef float type; static const size_t size = sizeof(type); type fVelU; static const uint8_t c = 1; static const uint8_t n = 39; void set(const uint8_t*& v){memcpy(&fVelU, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fVelU, sizeof(type)); v += sizeof(type); } }; typedef fVelU_t fVelU;
                    struct gps_longitude_origo_t { typedef int type; static const size_t size = sizeof(type); type gps_longitude_origo; static const uint8_t c = 1; static const uint8_t n = 40; void set(const uint8_t*& v){memcpy(&gps_longitude_origo, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_longitude_origo, sizeof(type)); v += sizeof(type); } }; typedef gps_longitude_origo_t gps_longitude_origo;
                    struct gps_latitude_origo_t { typedef int type; static const size_t size = sizeof(type); type gps_latitude_origo; static const uint8_t c = 1; static const uint8_t n = 41; void set(const uint8_t*& v){memcpy(&gps_latitude_origo, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_latitude_origo, sizeof(type)); v += sizeof(type); } }; typedef gps_latitude_origo_t gps_latitude_origo;
                    struct gps_altitude_origo_t { typedef int type; static const size_t size = sizeof(type); type gps_altitude_origo; static const uint8_t c = 1; static const uint8_t n = 42; void set(const uint8_t*& v){memcpy(&gps_altitude_origo, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_altitude_origo, sizeof(type)); v += sizeof(type); } }; typedef gps_altitude_origo_t gps_altitude_origo;
                    struct gps_origo_taken_t { typedef char type; static const size_t size = sizeof(type); type gps_origo_taken; static const uint8_t c = 1; static const uint8_t n = 43; void set(const uint8_t*& v){memcpy(&gps_origo_taken, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_origo_taken, sizeof(type)); v += sizeof(type); } }; typedef gps_origo_taken_t gps_origo_taken;
                    struct gps_longitude_m_t { typedef float type; static const size_t size = sizeof(type); type gps_longitude_m; static const uint8_t c = 1; static const uint8_t n = 44; void set(const uint8_t*& v){memcpy(&gps_longitude_m, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_longitude_m, sizeof(type)); v += sizeof(type); } }; typedef gps_longitude_m_t gps_longitude_m;
                    struct gps_latitude_m_t { typedef float type; static const size_t size = sizeof(type); type gps_latitude_m; static const uint8_t c = 1; static const uint8_t n = 45; void set(const uint8_t*& v){memcpy(&gps_latitude_m, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_latitude_m, sizeof(type)); v += sizeof(type); } }; typedef gps_latitude_m_t gps_latitude_m;
                    struct fHeadCF_t { typedef float type; static const size_t size = sizeof(type); type fHeadCF; static const uint8_t c = 1; static const uint8_t n = 46; void set(const uint8_t*& v){memcpy(&fHeadCF, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fHeadCF, sizeof(type)); v += sizeof(type); } }; typedef fHeadCF_t fHeadCF;
                }

                namespace SCMCU {
                    typedef request_part::DataRequestPart<MSG_CMCU_DATA_PART_REQUEST, 157> Part;

                    struct id_t { typedef int8_t type; static const size_t size = sizeof(type); type id; static const uint8_t c = 1; static const uint8_t n = 0; void set(const uint8_t*& v){memcpy(&id, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &id, sizeof(type)); v += sizeof(type); } }; typedef id_t id;
                    struct time_t { typedef uint32_t type; static const size_t size = sizeof(type); type time; static const uint8_t c = 1; static const uint8_t n = 1; void set(const uint8_t*& v){memcpy(&time, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &time, sizeof(type)); v += sizeof(type); } }; typedef time_t time;
                    struct logtime_t { typedef uint32_t type; static const size_t size = sizeof(type); type logtime; static const uint8_t c = 1; static const uint8_t n = 2; void set(const uint8_t*& v){memcpy(&logtime, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &logtime, sizeof(type)); v += sizeof(type); } }; typedef logtime_t logtime;
                    struct phi_t { typedef float type; static const size_t size = sizeof(type); type phi; static const uint8_t c = 1; static const uint8_t n = 3; void set(const uint8_t*& v){memcpy(&phi, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &phi, sizeof(type)); v += sizeof(type); } }; typedef phi_t phi;
                    struct theta_t { typedef float type; static const size_t size = sizeof(type); type theta; static const uint8_t c = 1; static const uint8_t n = 4; void set(const uint8_t*& v){memcpy(&theta, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &theta, sizeof(type)); v += sizeof(type); } }; typedef theta_t theta;
                    struct psi_t { typedef float type; static const size_t size = sizeof(type); type psi; static const uint8_t c = 1; static const uint8_t n = 5; void set(const uint8_t*& v){memcpy(&psi, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &psi, sizeof(type)); v += sizeof(type); } }; typedef psi_t psi;
                    struct compass_heading_t { typedef float type; static const size_t size = sizeof(type); type compass_heading; static const uint8_t c = 1; static const uint8_t n = 6; void set(const uint8_t*& v){memcpy(&compass_heading, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &compass_heading, sizeof(type)); v += sizeof(type); } }; typedef compass_heading_t compass_heading;
                    struct phi_dot_raw_t { typedef float type; static const size_t size = sizeof(type); type phi_dot_raw; static const uint8_t c = 1; static const uint8_t n = 7; void set(const uint8_t*& v){memcpy(&phi_dot_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &phi_dot_raw, sizeof(type)); v += sizeof(type); } }; typedef phi_dot_raw_t phi_dot_raw;
                    struct theta_dot_raw_t { typedef float type; static const size_t size = sizeof(type); type theta_dot_raw; static const uint8_t c = 1; static const uint8_t n = 8; void set(const uint8_t*& v){memcpy(&theta_dot_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &theta_dot_raw, sizeof(type)); v += sizeof(type); } }; typedef theta_dot_raw_t theta_dot_raw;
                    struct psi_dot_raw_t { typedef float type; static const size_t size = sizeof(type); type psi_dot_raw; static const uint8_t c = 1; static const uint8_t n = 9; void set(const uint8_t*& v){memcpy(&psi_dot_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &psi_dot_raw, sizeof(type)); v += sizeof(type); } }; typedef psi_dot_raw_t psi_dot_raw;
                    struct phi_dot_t { typedef float type; static const size_t size = sizeof(type); type phi_dot; static const uint8_t c = 1; static const uint8_t n = 10; void set(const uint8_t*& v){memcpy(&phi_dot, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &phi_dot, sizeof(type)); v += sizeof(type); } }; typedef phi_dot_t phi_dot;
                    struct theta_dot_t { typedef float type; static const size_t size = sizeof(type); type theta_dot; static const uint8_t c = 1; static const uint8_t n = 11; void set(const uint8_t*& v){memcpy(&theta_dot, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &theta_dot, sizeof(type)); v += sizeof(type); } }; typedef theta_dot_t theta_dot;
                    struct psi_dot_t { typedef float type; static const size_t size = sizeof(type); type psi_dot; static const uint8_t c = 1; static const uint8_t n = 12; void set(const uint8_t*& v){memcpy(&psi_dot, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &psi_dot, sizeof(type)); v += sizeof(type); } }; typedef psi_dot_t psi_dot;
                    struct siPhiTemp_t { typedef int16_t type; static const size_t size = sizeof(type); type siPhiTemp; static const uint8_t c = 1; static const uint8_t n = 13; void set(const uint8_t*& v){memcpy(&siPhiTemp, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &siPhiTemp, sizeof(type)); v += sizeof(type); } }; typedef siPhiTemp_t siPhiTemp;
                    struct siThetaTemp_t { typedef int16_t type; static const size_t size = sizeof(type); type siThetaTemp; static const uint8_t c = 1; static const uint8_t n = 14; void set(const uint8_t*& v){memcpy(&siThetaTemp, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &siThetaTemp, sizeof(type)); v += sizeof(type); } }; typedef siThetaTemp_t siThetaTemp;
                    struct siPsiTemp_t { typedef int16_t type; static const size_t size = sizeof(type); type siPsiTemp; static const uint8_t c = 1; static const uint8_t n = 15; void set(const uint8_t*& v){memcpy(&siPsiTemp, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &siPsiTemp, sizeof(type)); v += sizeof(type); } }; typedef siPsiTemp_t siPsiTemp;
                    struct accel_x_raw_t { typedef float type; static const size_t size = sizeof(type); type accel_x_raw; static const uint8_t c = 1; static const uint8_t n = 16; void set(const uint8_t*& v){memcpy(&accel_x_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &accel_x_raw, sizeof(type)); v += sizeof(type); } }; typedef accel_x_raw_t accel_x_raw;
                    struct accel_y_raw_t { typedef float type; static const size_t size = sizeof(type); type accel_y_raw; static const uint8_t c = 1; static const uint8_t n = 17; void set(const uint8_t*& v){memcpy(&accel_y_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &accel_y_raw, sizeof(type)); v += sizeof(type); } }; typedef accel_y_raw_t accel_y_raw;
                    struct accel_z_raw_t { typedef float type; static const size_t size = sizeof(type); type accel_z_raw; static const uint8_t c = 1; static const uint8_t n = 18; void set(const uint8_t*& v){memcpy(&accel_z_raw, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &accel_z_raw, sizeof(type)); v += sizeof(type); } }; typedef accel_z_raw_t accel_z_raw;
                    struct micromag_x_t { typedef float type; static const size_t size = sizeof(type); type micromag_x; static const uint8_t c = 1; static const uint8_t n = 19; void set(const uint8_t*& v){memcpy(&micromag_x, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &micromag_x, sizeof(type)); v += sizeof(type); } }; typedef micromag_x_t micromag_x;
                    struct micromag_y_t { typedef float type; static const size_t size = sizeof(type); type micromag_y; static const uint8_t c = 1; static const uint8_t n = 20; void set(const uint8_t*& v){memcpy(&micromag_y, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &micromag_y, sizeof(type)); v += sizeof(type); } }; typedef micromag_y_t micromag_y;
                    struct micromag_z_t { typedef float type; static const size_t size = sizeof(type); type micromag_z; static const uint8_t c = 1; static const uint8_t n = 21; void set(const uint8_t*& v){memcpy(&micromag_z, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &micromag_z, sizeof(type)); v += sizeof(type); } }; typedef micromag_z_t micromag_z;
                    struct hp_t { typedef float type; static const size_t size = sizeof(type); type hp; static const uint8_t c = 1; static const uint8_t n = 22; void set(const uint8_t*& v){memcpy(&hp, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &hp, sizeof(type)); v += sizeof(type); } }; typedef hp_t hp;
                    struct fPressureAltitude_t { typedef float type; static const size_t size = sizeof(type); type fPressureAltitude; static const uint8_t c = 1; static const uint8_t n = 23; void set(const uint8_t*& v){memcpy(&fPressureAltitude, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fPressureAltitude, sizeof(type)); v += sizeof(type); } }; typedef fPressureAltitude_t fPressureAltitude;
                    struct cGPSValid_t { typedef int8_t type; static const size_t size = sizeof(type); type cGPSValid; static const uint8_t c = 1; static const uint8_t n = 24; void set(const uint8_t*& v){memcpy(&cGPSValid, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &cGPSValid, sizeof(type)); v += sizeof(type); } }; typedef cGPSValid_t cGPSValid;
                    struct cGPSStatus_t { typedef uint8_t type; static const size_t size = sizeof(type); type cGPSStatus; static const uint8_t c = 1; static const uint8_t n = 25; void set(const uint8_t*& v){memcpy(&cGPSStatus, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &cGPSStatus, sizeof(type)); v += sizeof(type); } }; typedef cGPSStatus_t cGPSStatus;
                    struct iGpsLatDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type iGpsLatDeg; static const uint8_t c = 1; static const uint8_t n = 26; void set(const uint8_t*& v){memcpy(&iGpsLatDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsLatDeg, sizeof(type)); v += sizeof(type); } }; typedef iGpsLatDeg_t iGpsLatDeg;
                    struct iGpsLonDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type iGpsLonDeg; static const uint8_t c = 1; static const uint8_t n = 27; void set(const uint8_t*& v){memcpy(&iGpsLonDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsLonDeg, sizeof(type)); v += sizeof(type); } }; typedef iGpsLonDeg_t iGpsLonDeg;
                    struct iGpsAlt_t { typedef uint32_t type; static const size_t size = sizeof(type); type iGpsAlt; static const uint8_t c = 1; static const uint8_t n = 28; void set(const uint8_t*& v){memcpy(&iGpsAlt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsAlt, sizeof(type)); v += sizeof(type); } }; typedef iGpsAlt_t iGpsAlt;
                    struct ucGpsStatusFlags_t { typedef uint8_t type; static const size_t size = sizeof(type); type ucGpsStatusFlags; static const uint8_t c = 1; static const uint8_t n = 29; void set(const uint8_t*& v){memcpy(&ucGpsStatusFlags, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ucGpsStatusFlags, sizeof(type)); v += sizeof(type); } }; typedef ucGpsStatusFlags_t ucGpsStatusFlags;
                    struct gDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type gDop; static const uint8_t c = 1; static const uint8_t n = 30; void set(const uint8_t*& v){memcpy(&gDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gDop, sizeof(type)); v += sizeof(type); } }; typedef gDop_t gDop;
                    struct pDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type pDop; static const uint8_t c = 1; static const uint8_t n = 31; void set(const uint8_t*& v){memcpy(&pDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &pDop, sizeof(type)); v += sizeof(type); } }; typedef pDop_t pDop;
                    struct hDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type hDop; static const uint8_t c = 1; static const uint8_t n = 32; void set(const uint8_t*& v){memcpy(&hDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &hDop, sizeof(type)); v += sizeof(type); } }; typedef hDop_t hDop;
                    struct vDop_t { typedef uint16_t type; static const size_t size = sizeof(type); type vDop; static const uint8_t c = 1; static const uint8_t n = 33; void set(const uint8_t*& v){memcpy(&vDop, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &vDop, sizeof(type)); v += sizeof(type); } }; typedef vDop_t vDop;
                    struct num_SV_t { typedef uint8_t type; static const size_t size = sizeof(type); type num_SV; static const uint8_t c = 1; static const uint8_t n = 34; void set(const uint8_t*& v){memcpy(&num_SV, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &num_SV, sizeof(type)); v += sizeof(type); } }; typedef num_SV_t num_SV;
                    struct iGpsVelN_t { typedef int16_t type; static const size_t size = sizeof(type); type iGpsVelN; static const uint8_t c = 1; static const uint8_t n = 35; void set(const uint8_t*& v){memcpy(&iGpsVelN, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVelN, sizeof(type)); v += sizeof(type); } }; typedef iGpsVelN_t iGpsVelN;
                    struct iGpsVelE_t { typedef int16_t type; static const size_t size = sizeof(type); type iGpsVelE; static const uint8_t c = 1; static const uint8_t n = 36; void set(const uint8_t*& v){memcpy(&iGpsVelE, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVelE, sizeof(type)); v += sizeof(type); } }; typedef iGpsVelE_t iGpsVelE;
                    struct iGpsVelD_t { typedef int16_t type; static const size_t size = sizeof(type); type iGpsVelD; static const uint8_t c = 1; static const uint8_t n = 37; void set(const uint8_t*& v){memcpy(&iGpsVelD, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVelD, sizeof(type)); v += sizeof(type); } }; typedef iGpsVelD_t iGpsVelD;
                    struct iGpsSAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsSAcc; static const uint8_t c = 1; static const uint8_t n = 38; void set(const uint8_t*& v){memcpy(&iGpsSAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsSAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsSAcc_t iGpsSAcc;
                    struct iGpsPAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsPAcc; static const uint8_t c = 1; static const uint8_t n = 39; void set(const uint8_t*& v){memcpy(&iGpsPAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsPAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsPAcc_t iGpsPAcc;
                    struct iGpsHAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsHAcc; static const uint8_t c = 1; static const uint8_t n = 40; void set(const uint8_t*& v){memcpy(&iGpsHAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsHAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsHAcc_t iGpsHAcc;
                    struct iGpsVAcc_t { typedef uint16_t type; static const size_t size = sizeof(type); type iGpsVAcc; static const uint8_t c = 1; static const uint8_t n = 41; void set(const uint8_t*& v){memcpy(&iGpsVAcc, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &iGpsVAcc, sizeof(type)); v += sizeof(type); } }; typedef iGpsVAcc_t iGpsVAcc;
                    struct GpsHeadingDeg_t { typedef float type; static const size_t size = sizeof(type); type GpsHeadingDeg; static const uint8_t c = 1; static const uint8_t n = 42; void set(const uint8_t*& v){memcpy(&GpsHeadingDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &GpsHeadingDeg, sizeof(type)); v += sizeof(type); } }; typedef GpsHeadingDeg_t GpsHeadingDeg;
                    struct rc_sticks_0_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_0; static const uint8_t c = 1; static const uint8_t n = 43; void set(const uint8_t*& v){memcpy(&rc_sticks_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_0, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_0_t rc_sticks_0;
                    struct rc_sticks_1_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_1; static const uint8_t c = 1; static const uint8_t n = 44; void set(const uint8_t*& v){memcpy(&rc_sticks_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_1, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_1_t rc_sticks_1;
                    struct rc_sticks_2_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_2; static const uint8_t c = 1; static const uint8_t n = 45; void set(const uint8_t*& v){memcpy(&rc_sticks_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_2, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_2_t rc_sticks_2;
                    struct rc_sticks_3_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_3; static const uint8_t c = 1; static const uint8_t n = 46; void set(const uint8_t*& v){memcpy(&rc_sticks_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_3, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_3_t rc_sticks_3;
                    struct rc_sticks_4_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_4; static const uint8_t c = 1; static const uint8_t n = 47; void set(const uint8_t*& v){memcpy(&rc_sticks_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_4, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_4_t rc_sticks_4;
                    struct rc_sticks_5_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_5; static const uint8_t c = 1; static const uint8_t n = 48; void set(const uint8_t*& v){memcpy(&rc_sticks_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_5, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_5_t rc_sticks_5;
                    struct rc_sticks_6_t { typedef uint16_t type; static const size_t size = sizeof(type); type rc_sticks_6; static const uint8_t c = 1; static const uint8_t n = 49; void set(const uint8_t*& v){memcpy(&rc_sticks_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_sticks_6, sizeof(type)); v += sizeof(type); } }; typedef rc_sticks_6_t rc_sticks_6;
                    struct servo_output_0_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_0; static const uint8_t c = 1; static const uint8_t n = 50; void set(const uint8_t*& v){memcpy(&servo_output_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_0, sizeof(type)); v += sizeof(type); } }; typedef servo_output_0_t servo_output_0;
                    struct servo_output_1_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_1; static const uint8_t c = 1; static const uint8_t n = 51; void set(const uint8_t*& v){memcpy(&servo_output_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_1, sizeof(type)); v += sizeof(type); } }; typedef servo_output_1_t servo_output_1;
                    struct servo_output_2_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_2; static const uint8_t c = 1; static const uint8_t n = 52; void set(const uint8_t*& v){memcpy(&servo_output_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_2, sizeof(type)); v += sizeof(type); } }; typedef servo_output_2_t servo_output_2;
                    struct servo_output_3_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_3; static const uint8_t c = 1; static const uint8_t n = 53; void set(const uint8_t*& v){memcpy(&servo_output_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_3, sizeof(type)); v += sizeof(type); } }; typedef servo_output_3_t servo_output_3;
                    struct servo_output_4_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_4; static const uint8_t c = 1; static const uint8_t n = 54; void set(const uint8_t*& v){memcpy(&servo_output_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_4, sizeof(type)); v += sizeof(type); } }; typedef servo_output_4_t servo_output_4;
                    struct servo_output_5_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_5; static const uint8_t c = 1; static const uint8_t n = 55; void set(const uint8_t*& v){memcpy(&servo_output_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_5, sizeof(type)); v += sizeof(type); } }; typedef servo_output_5_t servo_output_5;
                    struct servo_output_6_t { typedef uint16_t type; static const size_t size = sizeof(type); type servo_output_6; static const uint8_t c = 1; static const uint8_t n = 56; void set(const uint8_t*& v){memcpy(&servo_output_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_output_6, sizeof(type)); v += sizeof(type); } }; typedef servo_output_6_t servo_output_6;
                    struct servo_mixer_input_0_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_0; static const uint8_t c = 1; static const uint8_t n = 57; void set(const uint8_t*& v){memcpy(&servo_mixer_input_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_0, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_0_t servo_mixer_input_0;
                    struct servo_mixer_input_1_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_1; static const uint8_t c = 1; static const uint8_t n = 58; void set(const uint8_t*& v){memcpy(&servo_mixer_input_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_1, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_1_t servo_mixer_input_1;
                    struct servo_mixer_input_2_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_2; static const uint8_t c = 1; static const uint8_t n = 59; void set(const uint8_t*& v){memcpy(&servo_mixer_input_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_2, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_2_t servo_mixer_input_2;
                    struct servo_mixer_input_3_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_3; static const uint8_t c = 1; static const uint8_t n = 60; void set(const uint8_t*& v){memcpy(&servo_mixer_input_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_3, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_3_t servo_mixer_input_3;
                    struct servo_mixer_input_4_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_4; static const uint8_t c = 1; static const uint8_t n = 61; void set(const uint8_t*& v){memcpy(&servo_mixer_input_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_4, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_4_t servo_mixer_input_4;
                    struct servo_mixer_input_5_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_5; static const uint8_t c = 1; static const uint8_t n = 62; void set(const uint8_t*& v){memcpy(&servo_mixer_input_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_5, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_5_t servo_mixer_input_5;
                    struct servo_mixer_input_6_t { typedef int16_t type; static const size_t size = sizeof(type); type servo_mixer_input_6; static const uint8_t c = 1; static const uint8_t n = 63; void set(const uint8_t*& v){memcpy(&servo_mixer_input_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &servo_mixer_input_6, sizeof(type)); v += sizeof(type); } }; typedef servo_mixer_input_6_t servo_mixer_input_6;
                    struct rc_aileron_at_ms_t { typedef uint8_t type; static const size_t size = sizeof(type); type rc_aileron_at_ms; static const uint8_t c = 1; static const uint8_t n = 64; void set(const uint8_t*& v){memcpy(&rc_aileron_at_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_aileron_at_ms, sizeof(type)); v += sizeof(type); } }; typedef rc_aileron_at_ms_t rc_aileron_at_ms;
                    struct rc_elevator_at_ms_t { typedef uint8_t type; static const size_t size = sizeof(type); type rc_elevator_at_ms; static const uint8_t c = 1; static const uint8_t n = 65; void set(const uint8_t*& v){memcpy(&rc_elevator_at_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_elevator_at_ms, sizeof(type)); v += sizeof(type); } }; typedef rc_elevator_at_ms_t rc_elevator_at_ms;
                    struct rc_rudder_at_ms_t { typedef uint8_t type; static const size_t size = sizeof(type); type rc_rudder_at_ms; static const uint8_t c = 1; static const uint8_t n = 66; void set(const uint8_t*& v){memcpy(&rc_rudder_at_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_rudder_at_ms, sizeof(type)); v += sizeof(type); } }; typedef rc_rudder_at_ms_t rc_rudder_at_ms;
                    struct rc_throttle_at_ms_t { typedef uint8_t type; static const size_t size = sizeof(type); type rc_throttle_at_ms; static const uint8_t c = 1; static const uint8_t n = 67; void set(const uint8_t*& v){memcpy(&rc_throttle_at_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_throttle_at_ms, sizeof(type)); v += sizeof(type); } }; typedef rc_throttle_at_ms_t rc_throttle_at_ms;
                    struct rc_camera_pan_at_ms_t { typedef uint8_t type; static const size_t size = sizeof(type); type rc_camera_pan_at_ms; static const uint8_t c = 1; static const uint8_t n = 68; void set(const uint8_t*& v){memcpy(&rc_camera_pan_at_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_camera_pan_at_ms, sizeof(type)); v += sizeof(type); } }; typedef rc_camera_pan_at_ms_t rc_camera_pan_at_ms;
                    struct rc_camera_tilt_at_ms_t { typedef uint8_t type; static const size_t size = sizeof(type); type rc_camera_tilt_at_ms; static const uint8_t c = 1; static const uint8_t n = 69; void set(const uint8_t*& v){memcpy(&rc_camera_tilt_at_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &rc_camera_tilt_at_ms, sizeof(type)); v += sizeof(type); } }; typedef rc_camera_tilt_at_ms_t rc_camera_tilt_at_ms;
                    struct targetLonDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type targetLonDeg; static const uint8_t c = 1; static const uint8_t n = 70; void set(const uint8_t*& v){memcpy(&targetLonDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &targetLonDeg, sizeof(type)); v += sizeof(type); } }; typedef targetLonDeg_t targetLonDeg;
                    struct targetLatDeg_t { typedef int32_t type; static const size_t size = sizeof(type); type targetLatDeg; static const uint8_t c = 1; static const uint8_t n = 71; void set(const uint8_t*& v){memcpy(&targetLatDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &targetLatDeg, sizeof(type)); v += sizeof(type); } }; typedef targetLatDeg_t targetLatDeg;
                    struct targetAltM_t { typedef float type; static const size_t size = sizeof(type); type targetAltM; static const uint8_t c = 1; static const uint8_t n = 72; void set(const uint8_t*& v){memcpy(&targetAltM, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &targetAltM, sizeof(type)); v += sizeof(type); } }; typedef targetAltM_t targetAltM;
                    struct targetHeadingDeg_t { typedef float type; static const size_t size = sizeof(type); type targetHeadingDeg; static const uint8_t c = 1; static const uint8_t n = 73; void set(const uint8_t*& v){memcpy(&targetHeadingDeg, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &targetHeadingDeg, sizeof(type)); v += sizeof(type); } }; typedef targetHeadingDeg_t targetHeadingDeg;
                    struct battery_voltage_t { typedef int16_t type; static const size_t size = sizeof(type); type battery_voltage; static const uint8_t c = 1; static const uint8_t n = 74; void set(const uint8_t*& v){memcpy(&battery_voltage, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &battery_voltage, sizeof(type)); v += sizeof(type); } }; typedef battery_voltage_t battery_voltage;
                    struct spi_status_t { typedef int8_t type; static const size_t size = sizeof(type); type spi_status; static const uint8_t c = 1; static const uint8_t n = 75; void set(const uint8_t*& v){memcpy(&spi_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &spi_status, sizeof(type)); v += sizeof(type); } }; typedef spi_status_t spi_status;
                    struct spi_crc_error_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type spi_crc_error_cnt; static const uint8_t c = 1; static const uint8_t n = 76; void set(const uint8_t*& v){memcpy(&spi_crc_error_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &spi_crc_error_cnt, sizeof(type)); v += sizeof(type); } }; typedef spi_crc_error_cnt_t spi_crc_error_cnt;
                    struct spi_tx_overflow_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type spi_tx_overflow_cnt; static const uint8_t c = 1; static const uint8_t n = 77; void set(const uint8_t*& v){memcpy(&spi_tx_overflow_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &spi_tx_overflow_cnt, sizeof(type)); v += sizeof(type); } }; typedef spi_tx_overflow_cnt_t spi_tx_overflow_cnt;
                    struct serial_1_crc_error_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type serial_1_crc_error_cnt; static const uint8_t c = 1; static const uint8_t n = 78; void set(const uint8_t*& v){memcpy(&serial_1_crc_error_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &serial_1_crc_error_cnt, sizeof(type)); v += sizeof(type); } }; typedef serial_1_crc_error_cnt_t serial_1_crc_error_cnt;
                    struct serial_1_tx_overflow_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type serial_1_tx_overflow_cnt; static const uint8_t c = 1; static const uint8_t n = 79; void set(const uint8_t*& v){memcpy(&serial_1_tx_overflow_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &serial_1_tx_overflow_cnt, sizeof(type)); v += sizeof(type); } }; typedef serial_1_tx_overflow_cnt_t serial_1_tx_overflow_cnt;
                    struct serial_2_crc_error_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type serial_2_crc_error_cnt; static const uint8_t c = 1; static const uint8_t n = 80; void set(const uint8_t*& v){memcpy(&serial_2_crc_error_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &serial_2_crc_error_cnt, sizeof(type)); v += sizeof(type); } }; typedef serial_2_crc_error_cnt_t serial_2_crc_error_cnt;
                    struct serial_2_tx_overflow_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type serial_2_tx_overflow_cnt; static const uint8_t c = 1; static const uint8_t n = 81; void set(const uint8_t*& v){memcpy(&serial_2_tx_overflow_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &serial_2_tx_overflow_cnt, sizeof(type)); v += sizeof(type); } }; typedef serial_2_tx_overflow_cnt_t serial_2_tx_overflow_cnt;
                    struct accel_status_t { typedef uint16_t type; static const size_t size = sizeof(type); type accel_status; static const uint8_t c = 1; static const uint8_t n = 82; void set(const uint8_t*& v){memcpy(&accel_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &accel_status, sizeof(type)); v += sizeof(type); } }; typedef accel_status_t accel_status;
                    struct remote_controller_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type remote_controller_status; static const uint8_t c = 1; static const uint8_t n = 83; void set(const uint8_t*& v){memcpy(&remote_controller_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &remote_controller_status, sizeof(type)); v += sizeof(type); } }; typedef remote_controller_status_t remote_controller_status;
                    struct flight_mode_t { typedef uint8_t type; static const size_t size = sizeof(type); type flight_mode; static const uint8_t c = 1; static const uint8_t n = 84; void set(const uint8_t*& v){memcpy(&flight_mode, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &flight_mode, sizeof(type)); v += sizeof(type); } }; typedef flight_mode_t flight_mode;
                    struct camera_mode_t { typedef uint8_t type; static const size_t size = sizeof(type); type camera_mode; static const uint8_t c = 1; static const uint8_t n = 85; void set(const uint8_t*& v){memcpy(&camera_mode, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &camera_mode, sizeof(type)); v += sizeof(type); } }; typedef camera_mode_t camera_mode;
                    struct logging_mode_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type logging_mode_status; static const uint8_t c = 1; static const uint8_t n = 86; void set(const uint8_t*& v){memcpy(&logging_mode_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &logging_mode_status, sizeof(type)); v += sizeof(type); } }; typedef logging_mode_status_t logging_mode_status;
                    struct logging_progress_t { typedef uint8_t type; static const size_t size = sizeof(type); type logging_progress; static const uint8_t c = 1; static const uint8_t n = 87; void set(const uint8_t*& v){memcpy(&logging_progress, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &logging_progress, sizeof(type)); v += sizeof(type); } }; typedef logging_progress_t logging_progress;
                    struct sdcard_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type sdcard_status; static const uint8_t c = 1; static const uint8_t n = 88; void set(const uint8_t*& v){memcpy(&sdcard_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &sdcard_status, sizeof(type)); v += sizeof(type); } }; typedef sdcard_status_t sdcard_status;
                    struct system_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type system_status; static const uint8_t c = 1; static const uint8_t n = 89; void set(const uint8_t*& v){memcpy(&system_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &system_status, sizeof(type)); v += sizeof(type); } }; typedef system_status_t system_status;
                    struct motor_status_t { typedef uint8_t type; static const size_t size = sizeof(type); type motor_status; static const uint8_t c = 1; static const uint8_t n = 90; void set(const uint8_t*& v){memcpy(&motor_status, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &motor_status, sizeof(type)); v += sizeof(type); } }; typedef motor_status_t motor_status;
                    struct adc_0_t { typedef uint16_t type; static const size_t size = sizeof(type); type adc_0; static const uint8_t c = 1; static const uint8_t n = 91; void set(const uint8_t*& v){memcpy(&adc_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &adc_0, sizeof(type)); v += sizeof(type); } }; typedef adc_0_t adc_0;
                    struct adc_1_t { typedef uint16_t type; static const size_t size = sizeof(type); type adc_1; static const uint8_t c = 1; static const uint8_t n = 92; void set(const uint8_t*& v){memcpy(&adc_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &adc_1, sizeof(type)); v += sizeof(type); } }; typedef adc_1_t adc_1;
                    struct adc_2_t { typedef uint16_t type; static const size_t size = sizeof(type); type adc_2; static const uint8_t c = 1; static const uint8_t n = 93; void set(const uint8_t*& v){memcpy(&adc_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &adc_2, sizeof(type)); v += sizeof(type); } }; typedef adc_2_t adc_2;
                    struct UserParamFloat_0_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_0; static const uint8_t c = 1; static const uint8_t n = 94; void set(const uint8_t*& v){memcpy(&UserParamFloat_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_0, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_0_t UserParamFloat_0;
                    struct UserParamFloat_1_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_1; static const uint8_t c = 1; static const uint8_t n = 95; void set(const uint8_t*& v){memcpy(&UserParamFloat_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_1, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_1_t UserParamFloat_1;
                    struct UserParamFloat_2_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_2; static const uint8_t c = 1; static const uint8_t n = 96; void set(const uint8_t*& v){memcpy(&UserParamFloat_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_2, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_2_t UserParamFloat_2;
                    struct UserParamFloat_3_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_3; static const uint8_t c = 1; static const uint8_t n = 97; void set(const uint8_t*& v){memcpy(&UserParamFloat_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_3, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_3_t UserParamFloat_3;
                    struct UserParamFloat_4_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_4; static const uint8_t c = 1; static const uint8_t n = 98; void set(const uint8_t*& v){memcpy(&UserParamFloat_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_4, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_4_t UserParamFloat_4;
                    struct UserParamFloat_5_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_5; static const uint8_t c = 1; static const uint8_t n = 99; void set(const uint8_t*& v){memcpy(&UserParamFloat_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_5, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_5_t UserParamFloat_5;
                    struct UserParamFloat_6_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_6; static const uint8_t c = 1; static const uint8_t n = 100; void set(const uint8_t*& v){memcpy(&UserParamFloat_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_6, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_6_t UserParamFloat_6;
                    struct UserParamFloat_7_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_7; static const uint8_t c = 1; static const uint8_t n = 101; void set(const uint8_t*& v){memcpy(&UserParamFloat_7, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_7, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_7_t UserParamFloat_7;
                    struct UserParamFloat_8_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_8; static const uint8_t c = 1; static const uint8_t n = 102; void set(const uint8_t*& v){memcpy(&UserParamFloat_8, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_8, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_8_t UserParamFloat_8;
                    struct UserParamFloat_9_t { typedef float type; static const size_t size = sizeof(type); type UserParamFloat_9; static const uint8_t c = 1; static const uint8_t n = 103; void set(const uint8_t*& v){memcpy(&UserParamFloat_9, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamFloat_9, sizeof(type)); v += sizeof(type); } }; typedef UserParamFloat_9_t UserParamFloat_9;
                    struct UserParamInt8_0_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_0; static const uint8_t c = 1; static const uint8_t n = 104; void set(const uint8_t*& v){memcpy(&UserParamInt8_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_0, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_0_t UserParamInt8_0;
                    struct UserParamInt8_1_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_1; static const uint8_t c = 1; static const uint8_t n = 105; void set(const uint8_t*& v){memcpy(&UserParamInt8_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_1, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_1_t UserParamInt8_1;
                    struct UserParamInt8_2_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_2; static const uint8_t c = 1; static const uint8_t n = 106; void set(const uint8_t*& v){memcpy(&UserParamInt8_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_2, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_2_t UserParamInt8_2;
                    struct UserParamInt8_3_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_3; static const uint8_t c = 1; static const uint8_t n = 107; void set(const uint8_t*& v){memcpy(&UserParamInt8_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_3, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_3_t UserParamInt8_3;
                    struct UserParamInt8_4_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_4; static const uint8_t c = 1; static const uint8_t n = 108; void set(const uint8_t*& v){memcpy(&UserParamInt8_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_4, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_4_t UserParamInt8_4;
                    struct UserParamInt8_5_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_5; static const uint8_t c = 1; static const uint8_t n = 109; void set(const uint8_t*& v){memcpy(&UserParamInt8_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_5, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_5_t UserParamInt8_5;
                    struct UserParamInt8_6_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_6; static const uint8_t c = 1; static const uint8_t n = 110; void set(const uint8_t*& v){memcpy(&UserParamInt8_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_6, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_6_t UserParamInt8_6;
                    struct UserParamInt8_7_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_7; static const uint8_t c = 1; static const uint8_t n = 111; void set(const uint8_t*& v){memcpy(&UserParamInt8_7, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_7, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_7_t UserParamInt8_7;
                    struct UserParamInt8_8_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_8; static const uint8_t c = 1; static const uint8_t n = 112; void set(const uint8_t*& v){memcpy(&UserParamInt8_8, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_8, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_8_t UserParamInt8_8;
                    struct UserParamInt8_9_t { typedef int8_t type; static const size_t size = sizeof(type); type UserParamInt8_9; static const uint8_t c = 1; static const uint8_t n = 113; void set(const uint8_t*& v){memcpy(&UserParamInt8_9, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt8_9, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt8_9_t UserParamInt8_9;
                    struct UserParamInt16_0_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_0; static const uint8_t c = 1; static const uint8_t n = 114; void set(const uint8_t*& v){memcpy(&UserParamInt16_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_0, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_0_t UserParamInt16_0;
                    struct UserParamInt16_1_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_1; static const uint8_t c = 1; static const uint8_t n = 115; void set(const uint8_t*& v){memcpy(&UserParamInt16_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_1, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_1_t UserParamInt16_1;
                    struct UserParamInt16_2_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_2; static const uint8_t c = 1; static const uint8_t n = 116; void set(const uint8_t*& v){memcpy(&UserParamInt16_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_2, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_2_t UserParamInt16_2;
                    struct UserParamInt16_3_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_3; static const uint8_t c = 1; static const uint8_t n = 117; void set(const uint8_t*& v){memcpy(&UserParamInt16_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_3, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_3_t UserParamInt16_3;
                    struct UserParamInt16_4_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_4; static const uint8_t c = 1; static const uint8_t n = 118; void set(const uint8_t*& v){memcpy(&UserParamInt16_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_4, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_4_t UserParamInt16_4;
                    struct UserParamInt16_5_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_5; static const uint8_t c = 1; static const uint8_t n = 119; void set(const uint8_t*& v){memcpy(&UserParamInt16_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_5, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_5_t UserParamInt16_5;
                    struct UserParamInt16_6_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_6; static const uint8_t c = 1; static const uint8_t n = 120; void set(const uint8_t*& v){memcpy(&UserParamInt16_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_6, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_6_t UserParamInt16_6;
                    struct UserParamInt16_7_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_7; static const uint8_t c = 1; static const uint8_t n = 121; void set(const uint8_t*& v){memcpy(&UserParamInt16_7, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_7, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_7_t UserParamInt16_7;
                    struct UserParamInt16_8_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_8; static const uint8_t c = 1; static const uint8_t n = 122; void set(const uint8_t*& v){memcpy(&UserParamInt16_8, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_8, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_8_t UserParamInt16_8;
                    struct UserParamInt16_9_t { typedef int16_t type; static const size_t size = sizeof(type); type UserParamInt16_9; static const uint8_t c = 1; static const uint8_t n = 123; void set(const uint8_t*& v){memcpy(&UserParamInt16_9, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt16_9, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt16_9_t UserParamInt16_9;
                    struct UserParamInt32_0_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_0; static const uint8_t c = 1; static const uint8_t n = 124; void set(const uint8_t*& v){memcpy(&UserParamInt32_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_0, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_0_t UserParamInt32_0;
                    struct UserParamInt32_1_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_1; static const uint8_t c = 1; static const uint8_t n = 125; void set(const uint8_t*& v){memcpy(&UserParamInt32_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_1, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_1_t UserParamInt32_1;
                    struct UserParamInt32_2_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_2; static const uint8_t c = 1; static const uint8_t n = 126; void set(const uint8_t*& v){memcpy(&UserParamInt32_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_2, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_2_t UserParamInt32_2;
                    struct UserParamInt32_3_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_3; static const uint8_t c = 1; static const uint8_t n = 127; void set(const uint8_t*& v){memcpy(&UserParamInt32_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_3, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_3_t UserParamInt32_3;
                    struct UserParamInt32_4_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_4; static const uint8_t c = 1; static const uint8_t n = 128; void set(const uint8_t*& v){memcpy(&UserParamInt32_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_4, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_4_t UserParamInt32_4;
                    struct UserParamInt32_5_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_5; static const uint8_t c = 1; static const uint8_t n = 129; void set(const uint8_t*& v){memcpy(&UserParamInt32_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_5, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_5_t UserParamInt32_5;
                    struct UserParamInt32_6_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_6; static const uint8_t c = 1; static const uint8_t n = 130; void set(const uint8_t*& v){memcpy(&UserParamInt32_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_6, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_6_t UserParamInt32_6;
                    struct UserParamInt32_7_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_7; static const uint8_t c = 1; static const uint8_t n = 131; void set(const uint8_t*& v){memcpy(&UserParamInt32_7, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_7, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_7_t UserParamInt32_7;
                    struct UserParamInt32_8_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_8; static const uint8_t c = 1; static const uint8_t n = 132; void set(const uint8_t*& v){memcpy(&UserParamInt32_8, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_8, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_8_t UserParamInt32_8;
                    struct UserParamInt32_9_t { typedef int32_t type; static const size_t size = sizeof(type); type UserParamInt32_9; static const uint8_t c = 1; static const uint8_t n = 133; void set(const uint8_t*& v){memcpy(&UserParamInt32_9, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &UserParamInt32_9, sizeof(type)); v += sizeof(type); } }; typedef UserParamInt32_9_t UserParamInt32_9;
                    struct fAltCF_t { typedef float type; static const size_t size = sizeof(type); type fAltCF; static const uint8_t c = 1; static const uint8_t n = 134; void set(const uint8_t*& v){memcpy(&fAltCF, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fAltCF, sizeof(type)); v += sizeof(type); } }; typedef fAltCF_t fAltCF;
                    struct fVelU_t { typedef float type; static const size_t size = sizeof(type); type fVelU; static const uint8_t c = 1; static const uint8_t n = 135; void set(const uint8_t*& v){memcpy(&fVelU, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fVelU, sizeof(type)); v += sizeof(type); } }; typedef fVelU_t fVelU;
                    struct gps_longitude_origo_t { typedef int32_t type; static const size_t size = sizeof(type); type gps_longitude_origo; static const uint8_t c = 1; static const uint8_t n = 136; void set(const uint8_t*& v){memcpy(&gps_longitude_origo, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_longitude_origo, sizeof(type)); v += sizeof(type); } }; typedef gps_longitude_origo_t gps_longitude_origo;
                    struct gps_latitude_origo_t { typedef int32_t type; static const size_t size = sizeof(type); type gps_latitude_origo; static const uint8_t c = 1; static const uint8_t n = 137; void set(const uint8_t*& v){memcpy(&gps_latitude_origo, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_latitude_origo, sizeof(type)); v += sizeof(type); } }; typedef gps_latitude_origo_t gps_latitude_origo;
                    struct gps_altitude_origo_t { typedef int32_t type; static const size_t size = sizeof(type); type gps_altitude_origo; static const uint8_t c = 1; static const uint8_t n = 138; void set(const uint8_t*& v){memcpy(&gps_altitude_origo, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_altitude_origo, sizeof(type)); v += sizeof(type); } }; typedef gps_altitude_origo_t gps_altitude_origo;
                    struct gps_longitude_m_t { typedef float type; static const size_t size = sizeof(type); type gps_longitude_m; static const uint8_t c = 1; static const uint8_t n = 139; void set(const uint8_t*& v){memcpy(&gps_longitude_m, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_longitude_m, sizeof(type)); v += sizeof(type); } }; typedef gps_longitude_m_t gps_longitude_m;
                    struct gps_latitude_m_t { typedef float type; static const size_t size = sizeof(type); type gps_latitude_m; static const uint8_t c = 1; static const uint8_t n = 140; void set(const uint8_t*& v){memcpy(&gps_latitude_m, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_latitude_m, sizeof(type)); v += sizeof(type); } }; typedef gps_latitude_m_t gps_latitude_m;
                    struct gps_origo_taken_t { typedef char type; static const size_t size = sizeof(type); type gps_origo_taken; static const uint8_t c = 1; static const uint8_t n = 141; void set(const uint8_t*& v){memcpy(&gps_origo_taken, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &gps_origo_taken, sizeof(type)); v += sizeof(type); } }; typedef gps_origo_taken_t gps_origo_taken;
                    struct fHeadCF_t { typedef float type; static const size_t size = sizeof(type); type fHeadCF; static const uint8_t c = 1; static const uint8_t n = 142; void set(const uint8_t*& v){memcpy(&fHeadCF, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &fHeadCF, sizeof(type)); v += sizeof(type); } }; typedef fHeadCF_t fHeadCF;
                    struct mixer_input_0_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_0_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 143; void set(const uint8_t*& v){memcpy(&mixer_input_0_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_0_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_0_at_fl_ms_t mixer_input_0_at_fl_ms;
                    struct mixer_input_1_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_1_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 144; void set(const uint8_t*& v){memcpy(&mixer_input_1_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_1_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_1_at_fl_ms_t mixer_input_1_at_fl_ms;
                    struct mixer_input_2_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_2_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 145; void set(const uint8_t*& v){memcpy(&mixer_input_2_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_2_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_2_at_fl_ms_t mixer_input_2_at_fl_ms;
                    struct mixer_input_3_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_3_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 146; void set(const uint8_t*& v){memcpy(&mixer_input_3_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_3_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_3_at_fl_ms_t mixer_input_3_at_fl_ms;
                    struct mixer_input_4_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_4_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 147; void set(const uint8_t*& v){memcpy(&mixer_input_4_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_4_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_4_at_fl_ms_t mixer_input_4_at_fl_ms;
                    struct mixer_input_5_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_5_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 148; void set(const uint8_t*& v){memcpy(&mixer_input_5_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_5_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_5_at_fl_ms_t mixer_input_5_at_fl_ms;
                    struct mixer_input_6_at_fl_ms_t { typedef int16_t type; static const size_t size = sizeof(type); type mixer_input_6_at_fl_ms; static const uint8_t c = 1; static const uint8_t n = 149; void set(const uint8_t*& v){memcpy(&mixer_input_6_at_fl_ms, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &mixer_input_6_at_fl_ms, sizeof(type)); v += sizeof(type); } }; typedef mixer_input_6_at_fl_ms_t mixer_input_6_at_fl_ms;
                    struct outer_loop_output_0_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_0; static const uint8_t c = 1; static const uint8_t n = 150; void set(const uint8_t*& v){memcpy(&outer_loop_output_0, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_0, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_0_t outer_loop_output_0;
                    struct outer_loop_output_1_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_1; static const uint8_t c = 1; static const uint8_t n = 151; void set(const uint8_t*& v){memcpy(&outer_loop_output_1, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_1, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_1_t outer_loop_output_1;
                    struct outer_loop_output_2_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_2; static const uint8_t c = 1; static const uint8_t n = 152; void set(const uint8_t*& v){memcpy(&outer_loop_output_2, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_2, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_2_t outer_loop_output_2;
                    struct outer_loop_output_3_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_3; static const uint8_t c = 1; static const uint8_t n = 153; void set(const uint8_t*& v){memcpy(&outer_loop_output_3, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_3, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_3_t outer_loop_output_3;
                    struct outer_loop_output_4_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_4; static const uint8_t c = 1; static const uint8_t n = 154; void set(const uint8_t*& v){memcpy(&outer_loop_output_4, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_4, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_4_t outer_loop_output_4;
                    struct outer_loop_output_5_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_5; static const uint8_t c = 1; static const uint8_t n = 155; void set(const uint8_t*& v){memcpy(&outer_loop_output_5, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_5, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_5_t outer_loop_output_5;
                    struct outer_loop_output_6_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_6; static const uint8_t c = 1; static const uint8_t n = 156; void set(const uint8_t*& v){memcpy(&outer_loop_output_6, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_6, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_6_t outer_loop_output_6;
                    struct outer_loop_output_7_t { typedef float type; static const size_t size = sizeof(type); type outer_loop_output_7; static const uint8_t c = 1; static const uint8_t n = 157; void set(const uint8_t*& v){memcpy(&outer_loop_output_7, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &outer_loop_output_7, sizeof(type)); v += sizeof(type); } }; typedef outer_loop_output_7_t outer_loop_output_7;
                }

                namespace SUser {
                    struct flags_t { typedef uint64_t type; static const size_t size = sizeof(type); type flags; static const uint8_t c = 1; static const uint8_t n = 0; void set(const uint8_t*& v){memcpy(&flags, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &flags, sizeof(type)); v += sizeof(type); } }; typedef flags_t flags;
                    struct params_32f_t { typedef float type[10]; static const size_t size = sizeof(type); type params_32f; static const uint8_t c = 1; static const uint8_t n = 1; void set(const uint8_t*& v){memcpy(&params_32f, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &params_32f, sizeof(type)); v += sizeof(type); } }; typedef params_32f_t params_32f;
                    struct params_8i_t { typedef int8_t type[10]; static const size_t size = sizeof(type); type params_8i; static const uint8_t c = 1; static const uint8_t n = 2; void set(const uint8_t*& v){memcpy(&params_8i, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &params_8i, sizeof(type)); v += sizeof(type); } }; typedef params_8i_t params_8i;
                    struct params_16i_t { typedef int16_t type[10]; static const size_t size = sizeof(type); type params_16i; static const uint8_t c = 1; static const uint8_t n = 3; void set(const uint8_t*& v){memcpy(&params_16i, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &params_16i, sizeof(type)); v += sizeof(type); } }; typedef params_16i_t params_16i;
                    struct params_32i_t { typedef int32_t type[10]; static const size_t size = sizeof(type); type params_32i; static const uint8_t c = 1; static const uint8_t n = 4; void set(const uint8_t*& v){memcpy(&params_32i, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &params_32i, sizeof(type)); v += sizeof(type); } }; typedef params_32i_t params_32i;
                }

                namespace SFlightTarget {
                    struct flags_t { typedef uint8_t type; static const size_t size = sizeof(type); type flags; static const uint8_t c = 1; static const uint8_t n = 0; void set(const uint8_t*& v){memcpy(&flags, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &flags, sizeof(type)); v += sizeof(type); } }; typedef flags_t flags;
                    struct longitude_t { typedef float type; static const size_t size = sizeof(type); type longitude; static const uint8_t c = 1; static const uint8_t n = 1; void set(const uint8_t*& v){memcpy(&longitude, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &longitude, sizeof(type)); v += sizeof(type); } }; typedef longitude_t longitude;
                    struct latitude_t { typedef float type; static const size_t size = sizeof(type); type latitude; static const uint8_t c = 1; static const uint8_t n = 2; void set(const uint8_t*& v){memcpy(&latitude, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &latitude, sizeof(type)); v += sizeof(type); } }; typedef latitude_t latitude;
                    struct altitude_t { typedef float type; static const size_t size = sizeof(type); type altitude; static const uint8_t c = 1; static const uint8_t n = 3; void set(const uint8_t*& v){memcpy(&altitude, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &altitude, sizeof(type)); v += sizeof(type); } }; typedef altitude_t altitude;
                    struct heading_t { typedef float type; static const size_t size = sizeof(type); type heading; static const uint8_t c = 1; static const uint8_t n = 4; void set(const uint8_t*& v){memcpy(&heading, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &heading, sizeof(type)); v += sizeof(type); } }; typedef heading_t heading;
                }

                namespace SCmd {
                    struct cId_t { typedef uint8_t type; static const size_t size = sizeof(type); type cId; static const uint8_t c = 1; static const uint8_t n = 1; void set(const uint8_t*& v){memcpy(&cId, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &cId, sizeof(type)); v += sizeof(type); } }; typedef cId_t cId;
                }

                #define tpldef(z,n,extra) PP_COMMA_IF(n) typename T##n extra
                 #define _nothing(z,n,c) PP_COMMA_IF(n) nothing
                  #define getn(z,w,d) PP_COMMA_IF(w) T##w::n
                   #define declv(z,w,d) PP_COMMA_IF(w) T##w v##w = NULL
                    #define setv(z,w,d) T##w::set(p);
                     #define getv(z,w,d) T##w::get(p);
                      #define szof(z,w,d) PP_PLUS_IF(w) T##w::size
                       #define getc(z,w,d) PP_PLUS_IF(w) T##w::c
                        #define tplname(z,n,q) PP_COMMA_IF(n) T##n
                        template<typename firstT = nothing, PP_REPEAT(MAX_NUM_DATAMEMBERS, tpldef, = nothing)> struct serial_data;
                        template<> struct serial_data<nothing, PP_REPEAT(MAX_NUM_DATAMEMBERS, _nothing,)> {};
                        template<typename firstT, PP_REPEAT(MAX_NUM_DATAMEMBERS, tpldef,)>
                        struct serial_data : public firstT, public serial_data<PP_REPEAT(MAX_NUM_DATAMEMBERS, tplname,)> {
                            static const uint8_t* get_ids() {
                               static const uint8_t _ids[MAX_NUM_DATAMEMBERS+1] = {firstT::n, PP_REPEAT(MAX_NUM_DATAMEMBERS, getn,)};
                               return _ids;
                            }
                            static uint8_t get_count() {
                                return firstT::c + PP_REPEAT(MAX_NUM_DATAMEMBERS, getc,);
                            }
                            packet_metadata_t metadata;
                            bool set(const uint8_t* p, size_t size) {
                               if(size != ( firstT::size + PP_REPEAT(MAX_NUM_DATAMEMBERS, szof, 0))) return false; // Size mismatch
                               firstT::set(p); PP_REPEAT(MAX_NUM_DATAMEMBERS, setv,0)
                               return true;
                            }
                            size_t marshal(unsigned char* p) {
                               unsigned char* q = p;
                               this->firstT::get(p); PP_REPEAT(MAX_NUM_DATAMEMBERS, getv,0)
                               return (size_t) (p-q);
                            }

                            serial_data() {
                              metadata.source = PACKET_UNDEFINED;
                              metadata.destination = PACKET_UNDEFINED;
                              metadata.sequence_number = PACKET_UNDEFINED;
                              metadata.packet_type = PACKET_UNDEFINED;
                            }
                        };
                       #undef getc
                      #undef szof
                     #undef getv
                    #undef setv
                   #undef declv
                  #undef getn
                 #undef _nothing
                #undef tpln



                namespace request_part {
                    struct everyNth_t { typedef uint16_t type; static const size_t size = sizeof(type); type everyNth; static const uint8_t c = 1; static const uint8_t n = 0; void set(const uint8_t*& v){memcpy(&everyNth, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &everyNth, sizeof(type)); v += sizeof(type); } }; typedef everyNth_t everyNth;
                    template<int N>
                    struct ids_t { typedef uint8_t type[N]; type ids; static const uint8_t c = 1; static const uint8_t n = 1; void set(const uint8_t*& v){memcpy(&ids, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ids, sizeof(type)); v += sizeof(type); } };
                    struct ids_cnt_t { typedef uint8_t type; static const size_t size = sizeof(type); type ids_cnt; static const uint8_t c = 1; static const uint8_t n = 2; void set(const uint8_t*& v){memcpy(&ids_cnt, v, sizeof(type)); v += sizeof(type); } void get(uint8_t*& v){memcpy(v, &ids_cnt, sizeof(type)); v += sizeof(type); } }; typedef ids_cnt_t ids_cnt;

                    template<int TYPE, int N>
                    struct DataRequestPart : public serial_data<request_part::everyNth_t, request_part::ids_t<N>, request_part::ids_cnt_t>
                    {
                        DataRequestPart(const uint8_t everyNth_, const uint8_t* ids_, const uint8_t ids_cnt_) {
                            assert(ids_cnt_ <= N);
                            everyNth_t::everyNth = everyNth_;
                            memcpy(ids_t<N>::ids, ids_, ids_cnt_);
                            ids_cnt_t::ids_cnt = ids_cnt_;
                            serial_data<request_part::everyNth_t, request_part::ids_t<N>, request_part::ids_cnt_t>
                                ::metadata.packet_type = TYPE;
                        }
                    };
                }
            }
        }
    }
}

#endif
